/**
 * Task-Runner RPC Command Generation Tests — TP-026 Step 4
 *
 * Source-extraction tests that validate the rpc-wrapper command structure
 * generated by spawnAgentTmux(), workspace-mode telemetry paths, and
 * /orch subprocess non-regression guarantees.
 *
 * These tests use source code extraction (reading task-runner.ts) to
 * validate structural contracts without requiring a running tmux session.
 *
 * Run: npx vitest run extensions/tests/task-runner-rpc.test.ts
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { readFileSync, existsSync, mkdirSync, rmSync } from "fs";
import { resolve, join } from "path";
import { tmpdir } from "os";

const TASK_RUNNER_PATH = resolve(__dirname, "../task-runner.ts");

function readTaskRunnerSource(): string {
	return readFileSync(TASK_RUNNER_PATH, "utf-8");
}

/**
 * Extract a region of source starting at `function <name>(` up to
 * the next `^function ` or section comment at the same indentation.
 *
 * This avoids the balanced-brace pitfall where TypeScript inline
 * type annotations (e.g., `opts: { ... }`) close prematurely.
 */
function extractFunctionRegion(src: string, funcName: string): string {
	const pattern = new RegExp(`function ${funcName}\\(`);
	const match = pattern.exec(src);
	if (!match) throw new Error(`Function ${funcName} not found in source`);

	const startIdx = match.index;

	// Find the next top-level function or section comment after this one.
	// We search for patterns like "\nfunction " or "\n// ── " that indicate
	// a new top-level declaration.
	const rest = src.slice(startIdx + 1);
	const nextFunc = rest.search(/\nfunction /);
	const nextSection = rest.search(/\n\/\/ ── /);

	let endOffset: number;
	if (nextFunc === -1 && nextSection === -1) {
		endOffset = rest.length;
	} else if (nextFunc === -1) {
		endOffset = nextSection;
	} else if (nextSection === -1) {
		endOffset = nextFunc;
	} else {
		endOffset = Math.min(nextFunc, nextSection);
	}

	return src.slice(startIdx, startIdx + 1 + endOffset);
}

// ── 1. Command Generation — spawnAgentTmux ──────────────────────────

describe("spawnAgentTmux command generation (source extraction)", () => {
	const src = readTaskRunnerSource();
	const tmuxBody = extractFunctionRegion(src, "spawnAgentTmux");

	it("uses resolveRpcWrapperPath() to locate the wrapper", () => {
		expect(tmuxBody).toContain("resolveRpcWrapperPath()");
	});

	it("passes --sidecar-path argument", () => {
		expect(tmuxBody).toContain('"--sidecar-path"');
	});

	it("passes --exit-summary-path argument", () => {
		expect(tmuxBody).toContain('"--exit-summary-path"');
	});

	it("passes --model argument", () => {
		expect(tmuxBody).toContain('"--model"');
	});

	it("passes --system-prompt-file argument", () => {
		expect(tmuxBody).toContain('"--system-prompt-file"');
	});

	it("passes --prompt-file argument", () => {
		expect(tmuxBody).toContain('"--prompt-file"');
	});

	it("passes --tools argument", () => {
		expect(tmuxBody).toContain('"--tools"');
	});

	it("passes --thinking via passthrough (after --)", () => {
		// --thinking should be passed via the -- passthrough section
		expect(tmuxBody).toContain('"--thinking"');
		// The passthrough delimiter should come before --thinking
		const dashDashIdx = tmuxBody.indexOf('"--"');
		const thinkingIdx = tmuxBody.indexOf('"--thinking"');
		expect(dashDashIdx).toBeGreaterThan(-1);
		expect(thinkingIdx).toBeGreaterThan(dashDashIdx);
	});

	it("passes --no-extensions and --no-skills via passthrough", () => {
		expect(tmuxBody).toContain('"--no-extensions"');
		expect(tmuxBody).toContain('"--no-skills"');
	});

	it("does NOT pass --no-session (rpc-wrapper injects it)", () => {
		// The wrapper itself adds --no-session when spawning pi.
		// spawnAgentTmux should NOT duplicate it in the command line.
		// Count occurrences of "--no-session" in the tmux function body
		const matches = tmuxBody.match(/"--no-session"/g);
		expect(matches).toBeNull();
	});

	it("uses 'node' as the command prefix (not 'pi')", () => {
		// The command is built as: node <rpc-wrapper-path> <args>
		expect(tmuxBody).toContain('"node"');
		expect(tmuxBody).toContain("wrapperArgs");
	});

	it("does NOT use 'pi -p --mode json' (that's the subprocess path)", () => {
		expect(tmuxBody).not.toContain('"--mode", "json"');
		expect(tmuxBody).not.toContain("spawn(\"pi\"");
	});

	it("writes system prompt and user prompt to temp files", () => {
		expect(tmuxBody).toContain("writeFileSync(sysTmpFile");
		expect(tmuxBody).toContain("writeFileSync(promptTmpFile");
	});

	it("uses quoteArg for shell safety", () => {
		expect(tmuxBody).toContain("quoteArg(rpcWrapperPath)");
		expect(tmuxBody).toContain("quoteArg(sidecarPath)");
		expect(tmuxBody).toContain("quoteArg(exitSummaryPath)");
		expect(tmuxBody).toContain("quoteArg(opts.model)");
		expect(tmuxBody).toContain("quoteArg(sysTmpFile)");
		expect(tmuxBody).toContain("quoteArg(promptTmpFile)");
		expect(tmuxBody).toContain("quoteArg(opts.tools)");
	});

	it("returns sidecarPath and exitSummaryPath in the result", () => {
		// The function return type includes these paths
		expect(tmuxBody).toContain("sidecarPath");
		expect(tmuxBody).toContain("exitSummaryPath");
	});

	it("handles TERM=xterm-256color wrapping for tmux", () => {
		expect(tmuxBody).toContain("TERM=xterm-256color");
	});

	it("converts Windows paths for tmux (MSYS2 path translation)", () => {
		// The CWD path is converted from C:\ to /c/ format for tmux
		expect(tmuxBody).toContain("tmuxCwd");
		expect(tmuxBody).toMatch(/replace\(\/\^.*\\\\\/,/);
	});
});

// ── 2. Telemetry filename contract ──────────────────────────────────

describe("telemetry filename contract (source extraction)", () => {
	const src = readTaskRunnerSource();
	const tmuxBody = extractFunctionRegion(src, "spawnAgentTmux");

	it("derives telemetry dir from getSidecarDir() + 'telemetry'", () => {
		expect(src).toContain('join(getSidecarDir(), "telemetry")');
	});

	it("sidecar filename follows {basename}.jsonl pattern", () => {
		expect(src).toContain("join(telemetryDir, `${telemetryBasename}.jsonl`)");
	});

	it("exit summary filename follows {basename}-exit.json pattern", () => {
		expect(src).toContain("join(telemetryDir, `${telemetryBasename}-exit.json`)");
	});

	it("basename includes opId, batchId, repoId, and role", () => {
		// The naming contract: {opId}-{batchId}-{repoId}[-{taskId}][-lane-{N}]-{role}
		expect(tmuxBody).toContain("telemetryBasename");
		expect(tmuxBody).toContain("opId");
		expect(tmuxBody).toContain("batchId");
		expect(tmuxBody).toContain("repoId");
		expect(tmuxBody).toContain("role");
	});

	it("supports optional taskId segment in basename", () => {
		expect(tmuxBody).toContain("taskIdSegment");
		expect(tmuxBody).toContain("opts.taskId");
	});

	it("supports optional lane suffix from sessionName", () => {
		expect(tmuxBody).toContain("laneMatch");
		expect(tmuxBody).toContain("laneSuffix");
	});

	it("uses Date.now() as batchId for uniqueness (no batch in standalone)", () => {
		expect(tmuxBody).toContain("telemetryTs = Date.now()");
		expect(tmuxBody).toContain("String(telemetryTs)");
	});

	it("resolves opId from TASKPLANE_OPERATOR_ID env, then OS username, then fallback 'op'", () => {
		expect(tmuxBody).toContain("TASKPLANE_OPERATOR_ID");
		expect(tmuxBody).toContain("userInfo()");
		expect(tmuxBody).toContain('"op"');
	});

	it("sanitizes opId to lowercase alphanumeric with hyphens, max 12 chars", () => {
		expect(tmuxBody).toContain(".toLowerCase()");
		expect(tmuxBody).toContain(".slice(0, 12)");
	});

	it("sanitizes taskId to filesystem-safe characters, max 30 chars", () => {
		expect(tmuxBody).toContain(".slice(0, 30)");
	});

	it("creates telemetry directory if it doesn't exist", () => {
		expect(tmuxBody).toContain('mkdirSync(telemetryDir, { recursive: true })');
	});
});

// ── 3. Workspace-mode telemetry path (dynamic) ─────────────────────

describe("workspace-mode telemetry path (getSidecarDir)", () => {
	let origEnv: string | undefined;
	let tmpDir: string;

	beforeEach(() => {
		origEnv = process.env.ORCH_SIDECAR_DIR;
		tmpDir = join(tmpdir(), `tp026-rpc-ws-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`);
		mkdirSync(tmpDir, { recursive: true });
	});

	afterEach(() => {
		if (origEnv === undefined) {
			delete process.env.ORCH_SIDECAR_DIR;
		} else {
			process.env.ORCH_SIDECAR_DIR = origEnv;
		}
		try { rmSync(tmpDir, { recursive: true, force: true }); } catch {}
	});

	it("returns ORCH_SIDECAR_DIR when set, creates it if needed", async () => {
		const sidecarDir = join(tmpDir, "workspace-pi");
		process.env.ORCH_SIDECAR_DIR = sidecarDir;

		const { _getSidecarDir } = await import("../task-runner.ts");
		const result = _getSidecarDir();
		expect(result).toBe(sidecarDir);
		expect(existsSync(sidecarDir)).toBe(true);
	});

	it("telemetry dir would be workspace-pi/telemetry/ in workspace mode", () => {
		// Structural test: verify the code joins getSidecarDir() + "telemetry"
		const src = readTaskRunnerSource();
		expect(src).toContain('join(getSidecarDir(), "telemetry")');
	});
});

// ── 4. /orch subprocess no-regression ───────────────────────────────

describe("/orch subprocess path no-regression (source extraction)", () => {
	const src = readTaskRunnerSource();

	it("spawnAgent() uses 'pi -p --mode json' (subprocess contract)", () => {
		const spawnAgentBody = extractFunctionRegion(src, "spawnAgent");
		expect(spawnAgentBody).toContain('"-p", "--mode", "json"');
		expect(spawnAgentBody).toContain('spawn("pi", args');
	});

	it("spawnAgent() does NOT reference rpc-wrapper", () => {
		const spawnAgentBody = extractFunctionRegion(src, "spawnAgent");
		expect(spawnAgentBody).not.toContain("rpc-wrapper");
		expect(spawnAgentBody).not.toContain("sidecar-path");
		expect(spawnAgentBody).not.toContain("exit-summary-path");
	});

	it("spawnAgent() preserves --no-session, --no-extensions, --no-skills", () => {
		const spawnAgentBody = extractFunctionRegion(src, "spawnAgent");
		expect(spawnAgentBody).toContain('"--no-session"');
		expect(spawnAgentBody).toContain('"--no-extensions"');
		expect(spawnAgentBody).toContain('"--no-skills"');
	});

	it("spawnAgent() uses --append-system-prompt (not --system-prompt-file)", () => {
		const spawnAgentBody = extractFunctionRegion(src, "spawnAgent");
		expect(spawnAgentBody).toContain('"--append-system-prompt"');
		expect(spawnAgentBody).not.toContain('"--system-prompt-file"');
	});

	it("pollUntilTaskComplete in execution.ts has no rpc-wrapper references", () => {
		const execSrc = readFileSync(
			resolve(__dirname, "../taskplane/execution.ts"),
			"utf-8",
		);
		expect(execSrc).toContain("export async function pollUntilTaskComplete(");
		expect(execSrc).not.toContain("rpc-wrapper");
		expect(execSrc).not.toContain("tailSidecarJsonl");
		expect(execSrc).not.toContain("readExitSummary");
		expect(execSrc).not.toContain("buildExitDiagnostic");
	});
});

// ── 5. resolveRpcWrapperPath strategy chain ─────────────────────────

describe("resolveRpcWrapperPath resolution strategy (source extraction)", () => {
	const src = readTaskRunnerSource();
	const resolverBody = extractFunctionRegion(src, "resolveRpcWrapperPath");

	it("has 5 resolution strategies", () => {
		// Strategy 1: Package root
		expect(resolverBody).toContain("findPackageRoot()");
		// Strategy 2: Project-local node_modules
		expect(resolverBody).toContain('node_modules", "taskplane"');
		// Strategy 3: Global npm paths
		expect(resolverBody).toContain("globalCandidates");
		// Strategy 4: Extension-file-relative
		expect(resolverBody).toContain('"-e"');
		expect(resolverBody).toContain("task-runner");
		// Strategy 5: Development fallback
		expect(resolverBody).toContain("process.cwd()");
	});

	it("resolves bin/rpc-wrapper.mjs relative path", () => {
		expect(resolverBody).toContain('"bin", "rpc-wrapper.mjs"');
	});

	it("throws a descriptive error when all strategies fail", () => {
		expect(resolverBody).toContain("Cannot find rpc-wrapper.mjs");
		expect(resolverBody).toContain("searched");
	});

	it("tracks searched paths for the error message", () => {
		expect(resolverBody).toContain("searched: string[]");
		expect(resolverBody).toContain("searched.push");
	});
});

// ── 6. spawnAgentTmux return shape ──────────────────────────────────

describe("spawnAgentTmux return shape contract", () => {
	const src = readTaskRunnerSource();

	it("returns { promise, kill, sidecarPath, exitSummaryPath }", () => {
		// Check the return type annotation
		const tmuxRegion = src.slice(
			src.indexOf("function spawnAgentTmux("),
			src.indexOf("function spawnAgentTmux(") + 800,
		);
		expect(tmuxRegion).toContain("promise:");
		expect(tmuxRegion).toContain("kill:");
		expect(tmuxRegion).toContain("sidecarPath:");
		expect(tmuxRegion).toContain("exitSummaryPath:");
	});

	it("spawnAgentTmux accepts onTelemetry callback", () => {
		const tmuxRegion = src.slice(
			src.indexOf("function spawnAgentTmux("),
			src.indexOf("function spawnAgentTmux(") + 1200,
		);
		expect(tmuxRegion).toContain("onTelemetry?:");
		expect(tmuxRegion).toContain("SidecarTelemetryDelta");
	});

	it("spawnAgentTmux accepts optional taskId for telemetry enrichment", () => {
		const tmuxRegion = src.slice(
			src.indexOf("function spawnAgentTmux("),
			src.indexOf("function spawnAgentTmux(") + 800,
		);
		expect(tmuxRegion).toContain("taskId?:");
	});
});

// ── 7. Sidecar tailing integration in poll loop ─────────────────────

describe("sidecar tailing integration in poll loop (source extraction)", () => {
	const src = readTaskRunnerSource();
	const tmuxBody = extractFunctionRegion(src, "spawnAgentTmux");

	it("creates a SidecarTailState for the session", () => {
		expect(tmuxBody).toContain("createSidecarTailState()");
	});

	it("calls tailSidecarJsonl on each poll tick", () => {
		expect(tmuxBody).toContain("tailSidecarJsonl(sidecarPath, tailState)");
	});

	it("gates onTelemetry callback on hadEvents", () => {
		expect(tmuxBody).toContain("delta.hadEvents");
		expect(tmuxBody).toContain("opts.onTelemetry");
	});

	it("performs a final tail after session ends", () => {
		// After has-session returns non-zero, there should be a final tail
		expect(tmuxBody).toContain("finalDelta");
	});

	it("handles stale session cleanup before creating new session", () => {
		expect(tmuxBody).toContain("killing stale session");
		expect(tmuxBody).toContain("kill-session");
	});
});
